using SmartNote.Maui.ViewModels;
using SmartNote.Maui.Models;

namespace SmartNote.Maui.Views;

public partial class StudyPlanView : ContentView
{
    private StudyPlanViewModel? _viewModel;
    
    public StudyPlanView()
    {
        InitializeComponent();
    }
    
    public StudyPlanView(StudyPlanViewModel viewModel) : this()
    {
        _viewModel = viewModel;
        BindingContext = viewModel;
    }
    
    protected override void OnHandlerChanged()
    {
        base.OnHandlerChanged();
        
        if (_viewModel == null && Handler?.MauiContext?.Services != null)
        {
            _viewModel = Handler.MauiContext.Services.GetService<StudyPlanViewModel>();
            if (_viewModel != null) BindingContext = _viewModel;
        }
        
        if (_viewModel != null)
        {
            _ = _viewModel.LoadDataCommand.ExecuteAsync(null);
        }
    }
    
    private void OnSessionCheckedChanged(object? sender, CheckedChangedEventArgs e)
    {
        if (sender is CheckBox checkBox && checkBox.BindingContext is StudySession session && _viewModel != null)
        {
            // Execute the toggle command - uses ToggleSessionAsyncCommand generated by [RelayCommand]
            _ = _viewModel.ToggleSessionAsyncCommand.ExecuteAsync(session);
        }
    }
}
