using SmartNote.Maui.ViewModels;
using SmartNote.Maui.Models;

namespace SmartNote.Maui.Views;

public partial class TasksView : ContentView
{
    private TasksViewModel? _viewModel;
    
    public TasksView()
    {
        InitializeComponent();
    }
    
    public TasksView(TasksViewModel viewModel) : this()
    {
        _viewModel = viewModel;
        BindingContext = viewModel;
    }
    
    protected override void OnHandlerChanged()
    {
        base.OnHandlerChanged();
        
        if (_viewModel == null && Handler?.MauiContext?.Services != null)
        {
            _viewModel = Handler.MauiContext.Services.GetService<TasksViewModel>();
            if (_viewModel != null) BindingContext = _viewModel;
        }
        
        if (_viewModel != null)
        {
            _ = _viewModel.LoadDataCommand.ExecuteAsync(null);
        }
    }
    
    private void OnTaskCheckedChanged(object? sender, CheckedChangedEventArgs e)
    {
        if (sender is CheckBox checkBox && checkBox.BindingContext is TaskItem task && _viewModel != null)
        {
            // Execute the toggle command - uses ToggleTaskCommand generated by [RelayCommand]
            _ = _viewModel.ToggleTaskCommand.ExecuteAsync(task);
        }
    }
}
